global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: 'publoader'
    static_configs:
      - targets: ['publoader:8080']
  - job_name: 'publoader-extensions'
    static_configs:
      - targets: ['publoader-extensions:8080']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

rule_files:
  - 'alert.rules.yml'
