services:
  publoader:
    image: ardax/publoader:latest
    container_name: publoader
    restart: unless-stopped
    ports:
      - "8080:8080"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - ./config.ini:/app/config.ini
      - ./logs:/app/logs
      - extensions:/app/publoader/extensions
      - ./entrypoint.sh:/app/entrypoint.sh
    entrypoint: [ "/app/entrypoint.sh" ]
    command: [ "python", "run.py" ]

  publoader-extensions:
    image: ardax/publoader-extensions:latest
    container_name: publoader-extensions
    restart: "no"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - extensions:/shared/publoader/extensions

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 1 * * * # 1am GMT daily
    depends_on:
      - publoader
      - publoader-extensions

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - publoader
      - publoader-extensions

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_PUBLOADER_TUNNEL_TOKEN}
    depends_on:
      - grafana

volumes:
  grafana_data:
  extensions:
