services:
  publoader:
    image: ardax/publoader:latest
    container_name: publoader
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config.ini:/app/config.ini
      - ./logs:/app/logs
      - extensions:/app/publoader/extensions
      - ./entrypoint.sh:/app/entrypoint.sh
    entrypoint: [ "/app/entrypoint.sh" ]
    command: [ "python", "run.py" ]

  publoader-extensions:
    image: ardax/publoader-extensions:latest
    container_name: publoader-extensions
    restart: "no"
    volumes:
      - extensions:/shared/publoader/extensions
    # This ensures the container stays running to maintain the volume
    command: ["tail", "-f", "/dev/null"]

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_PUBLOADER_TUNNEL_TOKEN}

volumes:
  extensions: