name: Reject Pull Requests

on:
  pull_request:
    types: 
      - opened
      - reopened
    branches:
      - master
      - main



jobs:
  reject-pull:
    runs-on: ubuntu-latest
    name: Prevent file change
    permissions:
      pull-requests: read
    steps:
    - uses: xalvarez/prevent-file-change-action@v1
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        pattern: ^(?!manga\.json|title_regex\.json).*$
        trustedAuthors: ArdaxHz, Korbeil, curche
